// Generated by CoffeeScript 2.5.1
// export download = (tree, fileName) =>
// 	blob = new Blob [JSON.stringify tree], type: 'application/json'
// 	a = document.createElement 'a'
// 	a.download = fileName
// 	a.href = URL.createObjectURL blob
// 	a.target = '_blank'
// 	a.click()
// 	URL.revokeObjectURL a.href

//document.querySelector('button').onclick = () =>
//downloadFile 'https://www.google-analytics.com/analytics.js', 'gooleAnalytics.js'


//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZG93bmxvYWQuanMiLCJzb3VyY2VSb290IjoiLi4iLCJzb3VyY2VzIjpbImNvZmZlZVxcZG93bmxvYWQuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFVbUYiLCJzb3VyY2VzQ29udGVudCI6WyIjIGV4cG9ydCBkb3dubG9hZCA9ICh0cmVlLCBmaWxlTmFtZSkgPT5cclxuIyBcdGJsb2IgPSBuZXcgQmxvYiBbSlNPTi5zdHJpbmdpZnkgdHJlZV0sIHR5cGU6ICdhcHBsaWNhdGlvbi9qc29uJ1xyXG4jIFx0YSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQgJ2EnXHJcbiMgXHRhLmRvd25sb2FkID0gZmlsZU5hbWVcclxuIyBcdGEuaHJlZiA9IFVSTC5jcmVhdGVPYmplY3RVUkwgYmxvYlxyXG4jIFx0YS50YXJnZXQgPSAnX2JsYW5rJ1xyXG4jIFx0YS5jbGljaygpXHJcbiMgXHRVUkwucmV2b2tlT2JqZWN0VVJMIGEuaHJlZlxyXG5cclxuXHQjZG9jdW1lbnQucXVlcnlTZWxlY3RvcignYnV0dG9uJykub25jbGljayA9ICgpID0+XHJcblx0I2Rvd25sb2FkRmlsZSAnaHR0cHM6Ly93d3cuZ29vZ2xlLWFuYWx5dGljcy5jb20vYW5hbHl0aWNzLmpzJywgJ2dvb2xlQW5hbHl0aWNzLmpzJyJdfQ==
//# sourceURL=c:\github\2023-022-ChessOpenings-SpacedRepetition\coffee\download.coffee